version: '2'

services:
  goerli:
    image: tornadocash/relayer:v3.0.2
    restart: always
    environment:
      VIRTUAL_HOST: relayerbruno.duckdns.org
      LETSENCRYPT_HOST: relayerbruno.duckdns.org
      NET_ID: 5
      RPC_URL: https://goerli.infura.io/v3/a63a99bfc4464dad88623244bbb2f66b
      # ORACLE_RPC_URL should always point to the mainnet
      ORACLE_RPC_URL: https://mainnet.infura.io/v3/a63a99bfc4464dad88623244bbb2f66b
      # without 0x prefix
      PRIVATE_KEY: d0fb4395956b1eb07de2b50a657aba651e50bee7c3c502d83a669a5b32f06541
      # 2.5 means 2.5%
      RELAYER_FEE: 0.0
      REDIS_URL: redis://redis/0
      nginx_proxy_read_timeout: 600
    depends_on:
      - redis

  mainnet:
    image: tornadocash/relayer:v3.0.2
    restart: always
    environment:
      VIRTUAL_HOST: relayertornado.duckdns.org
      LETSENCRYPT_HOST: relayertornado.duckdns.org
      NET_ID: 1
      RPC_URL: https://mainnet.infura.io/v3/ec5e67121a054ca99eee09da0495afb9
      # ORACLE_RPC_URL should always point to the mainnet
      ORACLE_RPC_URL: https://mainnet.infura.io/v3/ec5e67121a054ca99eee09da0495afb9
      # without 0x prefix
      PRIVATE_KEY: d0fb4395956b1eb07de2b50a657aba651e50bee7c3c502d83a669a5b32f06541
      # 2.5 means 2.5%
      RELAYER_FEE: 0.0
      REDIS_URL: redis://redis/1
      nginx_proxy_read_timeout: 600
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    command: [redis-server, --appendonly, 'yes']
    volumes:
      - redis:/data

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
    logging:
      driver: none

  dockergen:
    image: poma/docker-gen
    container_name: dockergen
    restart: always
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      NGINX_DOCKER_GEN_CONTAINER: dockergen
    volumes_from:
      - nginx
      - dockergen

volumes:
  conf:
  vhost:
  html:
  certs:
  redis:

